Args = --initialize-at-build-time=kotlinx.coroutines,kotlinx.serialization,kotlin,it.krzeminski.snakeyaml,com.charleskorn.kaml,net.thauvin.erik.urlencoder \
       --initialize-at-run-time=io.qorche \
       -H:+ReportExceptionStackTraces
